package memory

import "errors"

var (
	ErrInvalidSpaceID           = errors.New("invalid space id")
	ErrInvalidMemoryID          = errors.New("invalid memory id")
	ErrInvalidContent           = errors.New("invalid content")
	ErrInvalidActorID           = errors.New("invalid actor id")
	ErrInvalidActorKind         = errors.New("invalid actor kind")
	ErrInvalidMemoryKind        = errors.New("invalid memory kind")
	ErrInvalidConfidence        = errors.New("invalid confidence")
	ErrInvalidTrustLevel        = errors.New("invalid trust level")
	ErrInvalidDimension         = errors.New("invalid dimension")
	ErrInvalidDefaultWeight     = errors.New("invalid default weight")
	ErrInvalidHalfLife          = errors.New("invalid half life")
	ErrInvalidMemoryVersion     = errors.New("invalid memory version")
	ErrInvalidWritersPolicy     = errors.New("invalid writers policy")
	ErrInvalidSpaceConfig       = errors.New("invalid space config")
	ErrInvalidSpaceWritePolicy  = errors.New("invalid space write policy")
	ErrInvalidSpaceInit         = errors.New("invalid space init")
	ErrNilEmbedder              = errors.New("nil embedder")
	ErrEmbedderUnavailable      = errors.New("embedder unavailable")
	ErrEmbeddingModelMismatch   = errors.New("embedding model mismatch")
	ErrSpaceMigrating           = errors.New("space is migrating")
	ErrStoreClosed              = errors.New("store closed")
	ErrConflict                 = errors.New("write conflict")
	ErrMemoryNotFound           = errors.New("memory not found")
	ErrSpaceNotFound            = errors.New("space not found")
	ErrLineageActive            = errors.New("lineage is active")
	ErrReviveDerivedUnsupported = errors.New("revive for derived lineages is not supported")
	ErrInvalidRelations         = errors.New("invalid relations")
	ErrPolicyViolation          = errors.New("policy violation")
	ErrCorpusLimit              = errors.New("corpus limit reached")
	ErrUpdateTargetNotFound     = errors.New("update target not found")
	ErrUpdateTargetNotLatest    = errors.New("update target is not latest")
	ErrUpdateTargetForgotten    = errors.New("update target is forgotten")
	ErrUpdateAcrossSpaces       = errors.New("update target is in a different space")
	ErrUpdateAcrossKinds        = errors.New("update target has a different kind")
	ErrExtendsTargetNotFound    = errors.New("extends target not found")
	ErrExtendsTargetNotLatest   = errors.New("extends target is not latest")
	ErrExtendsTargetForgotten   = errors.New("extends target is forgotten")
	ErrExtendsAcrossSpaces      = errors.New("extends target is in a different space")
	ErrDerivedSourceCount       = errors.New("derived memory requires at least two distinct sources")
	ErrDerivedSourceNotFound    = errors.New("derived source not found")
	ErrDerivedSourceNotLatest   = errors.New("derived source is not latest")
	ErrDerivedSourceForgotten   = errors.New("derived source is forgotten")
	ErrDerivedAcrossSpaces      = errors.New("derived source is in a different space")
	ErrDerivedSourceKind        = errors.New("derived source has invalid kind")
	ErrDerivedRationale         = errors.New("derived rationale is required")
	ErrDerivedActorKind         = errors.New("derived actor kind is not allowed")
)
